FROM node:22-alpine AS build

WORKDIR /app
COPY package.json tsconfig.json ./
COPY src ./src
RUN npm install && npm run build

FROM node:22-alpine

WORKDIR /app
COPY --from=build /app/dist ./dist

CMD ["node", "dist/main.js"]
