package openriak.erlang.codegen;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.core.BeamNameUtils;
import io.smithy.beam.erlang.ErlangContext;
import io.smithy.beam.erlang.ErlangWriter;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBinding;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.knowledge.TopDownIndex;
import software.amazon.smithy.model.shapes.BlobShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.traits.ErrorTrait;
import software.amazon.smithy.model.traits.HttpErrorTrait;
import software.amazon.smithy.model.traits.HttpTrait;
import software.amazon.smithy.model.traits.StreamingTrait;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Set;

/**
 * openRiakHttp codec emitter for Erlang. HTTP framing follows smithy-beam REST helpers;
 * opaque {@code @httpPayload} bodies pass through without JSON document encoding.
 */
public final class ErlangOpenRiakHttpEmitter {

    public static final String CODEC_SUFFIX = "http";

    private ErlangOpenRiakHttpEmitter() {}

    public static String codecModuleName(BeamErlangLayout layout) {
        return layout.clientModuleName().replace("_client", "") + "_" + CODEC_SUFFIX;
    }

    public static void emitCodecModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String codecFile = codecModuleName(layout) + ".erl";
        String codecModule = codecModuleName(layout);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        List<OperationShape> operations = containedOperationsSorted(model, service);
        List<String> exports = new ArrayList<>();
        for (OperationShape op : operations) {
            String name = sp.toSymbol(op).getName();
            exports.add("encode_" + name + "_request/1");
            exports.add("decode_" + name + "_response/1");
        }

        ctx.writerDelegator().useFileWriter(codecFile, writer -> {
            writer.write("%% openRiakHttp codecs for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by openriak-erlang-codegen.");
            writer.write("-module($L).", codecModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            writer.write("-include(\"$L\").", layout.runtimeTypesHeaderFile());
            writer.write("-export([$L]).", String.join(",\n    ", exports));
            writer.write("");

            for (OperationShape op : operations) {
                emitEncoder(writer, model, op, httpIndex, sp);
                emitDecoder(writer, model, op, httpIndex, sp);
            }

            for (OperationShape op : operations) {
                emitErrorDispatch(writer, model, op, sp);
            }

            emitHelpers(writer);
        });
    }

    public static void emitOperation(ErlangContext ctx, ServiceShape service, OperationShape operation) {
        // Full codec module is emitted once in customize via emitCodecModule.
    }

    private static void emitEncoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape input = model.expectShape(op.getInputShape(), StructureShape.class);
        String inputRecord = recordName(sp.toSymbol(input));
        String inputType = sp.toSymbol(input).getName();
        HttpTrait httpTrait = op.expectTrait(HttpTrait.class);
        String method = httpTrait.getMethod();
        String uriTemplate = httpTrait.getUri().toString();

        List<HttpBinding> labels = httpIndex.getRequestBindings(op, HttpBinding.Location.LABEL);
        List<HttpBinding> queries = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY);
        List<HttpBinding> queryParams = httpIndex.getRequestBindings(op, HttpBinding.Location.QUERY_PARAMS);
        List<HttpBinding> headers = httpIndex.getRequestBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> prefixHeaders = httpIndex.getRequestBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> reqPayload = httpIndex.getRequestBindings(op, HttpBinding.Location.PAYLOAD);

        List<String> patternParts = buildPatternParts(
                sp, labels, queries, queryParams, headers, prefixHeaders, reqPayload);
        String pattern = patternParts.isEmpty() ? "" : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("%% Encode HTTP request for $L.", op.getId());
        writer.write("-spec encode_$L_request($L) -> #http_request{}.", opName, inputType);
        writer.write("encode_$L_request(Input = #$L{$L}) ->", opName, inputRecord, pattern);
        writer.indent();

        String pathExpr = buildPathExpression(uriTemplate, labels, sp);
        writer.write("Path = $L,", pathExpr);

        if (queries.isEmpty()) {
            writer.write("HttpQuery = [],");
        } else {
            writer.write("HttpQuery = lists:filtermap(fun");
            for (HttpBinding qb : queries) {
                String paramName = qb.getLocationName();
                String fieldName = memberFieldName(sp, qb.getMember());
                writer.write(
                        "    ({<<\"$L\">>, V}) when V =/= undefined -> {true, {<<\"$L\">>, encode_query_value(V)}};",
                        fieldName, paramName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    queries.stream()
                            .map(qb -> "{" + queryTupleKey(sp, qb) + ", "
                                    + toBindingVar(memberFieldName(sp, qb.getMember())) + "}")
                            .reduce((a, b) -> a + ", " + b)
                            .orElse(""));
        }

        for (HttpBinding qp : queryParams) {
            String fieldName = memberFieldName(sp, qp.getMember());
            String bindingVar = toBindingVar(fieldName);
            writer.write("HttpQueryExtra = case $L of", bindingVar);
            writer.indent();
            writer.write("undefined -> [];");
            writer.write("M when is_map(M) ->");
            writer.indent();
            writer.write("[{K, V} || {K, V} <- maps:to_list(M)]");
            writer.dedent();
            writer.dedent();
            writer.write("end,");
            writer.write("HttpQuery = HttpQuery ++ HttpQueryExtra,");
        }

        if (headers.isEmpty()) {
            writer.write("Headers = [],");
        } else {
            writer.write("Headers = lists:filtermap(fun");
            for (HttpBinding hb : headers) {
                String headerName = hb.getLocationName();
                String fieldName = memberFieldName(sp, hb.getMember());
                writer.write(
                        "    ({<<\"$L\">>, V}) when V =/= undefined -> {true, {<<\"$L\">>, to_binary(V)}};",
                        fieldName, headerName);
            }
            writer.write("    (_) -> false");
            writer.write("end, [$L]),",
                    headers.stream()
                            .map(hb -> "{" + headerTupleKey(sp, hb) + ", "
                                    + toBindingVar(memberFieldName(sp, hb.getMember())) + "}")
                            .reduce((a, b) -> a + ", " + b)
                            .orElse(""));
        }

        for (HttpBinding ph : prefixHeaders) {
            String fieldName = memberFieldName(sp, ph.getMember());
            String prefix = ph.getLocationName();
            writer.write("Headers = Headers ++ prefix_headers_to_list(<<\"$L\">>, $L),",
                    prefix, toBindingVar(fieldName));
        }

        emitOpaqueRequestBody(writer, model, reqPayload, method, sp);

        writer.write("#http_request{");
        writer.write("    method = <<\"$L\">>,", method);
        writer.write("    path = Path,");
        writer.write("    query = maps:from_list(HttpQuery),");
        writer.write("    headers = Headers,");
        writer.write("    body = Body");
        writer.write("}.");
        writer.dedent();
        writer.write("");
    }

    private static void emitDecoder(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            HttpBindingIndex httpIndex,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        StructureShape output = model.expectShape(op.getOutputShape(), StructureShape.class);
        String outputRecord = recordName(sp.toSymbol(output));
        String outputType = sp.toSymbol(output).getName();
        int successCode = httpIndex.getResponseCode(op);

        List<HttpBinding> respHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.HEADER);
        List<HttpBinding> respPrefixHeaders = httpIndex.getResponseBindings(op, HttpBinding.Location.PREFIX_HEADERS);
        List<HttpBinding> respPayload = httpIndex.getResponseBindings(op, HttpBinding.Location.PAYLOAD);
        List<HttpBinding> respCode = httpIndex.getResponseBindings(op, HttpBinding.Location.RESPONSE_CODE);

        writer.write("%% Decode HTTP response for $L.", op.getId());
        writer.write("-spec decode_$L_response(#http_response{}) -> {'ok', $L} | {'error', term()}.",
                opName, outputType);
        if (!respCode.isEmpty()) {
            writer.write(
                    "decode_$L_response(#http_response{status = HttpStatus, headers = Headers, body = Body})"
                            + " when HttpStatus >= 200, HttpStatus < 300 ->",
                    opName);
        } else {
            writer.write("decode_$L_response(#http_response{status = $L, headers = Headers, body = Body}) ->",
                    opName, successCode);
        }
        writer.indent();

        for (HttpBinding hb : respHeaders) {
            String fieldName = memberFieldName(sp, hb.getMember());
            String bindingVar = toBindingVar(fieldName);
            String headerName = hb.getLocationName();
            writer.write("$L = proplists:get_value(<<\"$L\">>, Headers, undefined),",
                    bindingVar, headerName);
        }

        List<String> recordFields = new ArrayList<>();
        for (HttpBinding hb : respHeaders) {
            String fieldName = memberFieldName(sp, hb.getMember());
            recordFields.add("    " + fieldName + " = " + toBindingVar(fieldName));
        }
        for (HttpBinding ph : respPrefixHeaders) {
            String fieldName = memberFieldName(sp, ph.getMember());
            String prefix = ph.getLocationName();
            recordFields.add("    " + fieldName + " = prefix_headers_from_list(Headers, <<\"" + prefix + "\">>)");
        }
        for (HttpBinding pb : respPayload) {
            String fieldName = memberFieldName(sp, pb.getMember());
            if (isStreamingBlob(model, pb.getMember())) {
                recordFields.add("    " + fieldName + " = Body");
            } else {
                recordFields.add("    " + fieldName + " = Body");
            }
        }
        for (HttpBinding rcb : respCode) {
            String fieldName = memberFieldName(sp, rcb.getMember());
            recordFields.add("    " + fieldName + " = HttpStatus");
        }

        if (recordFields.isEmpty() && !respCode.isEmpty()) {
            recordFields.add("    status_code = HttpStatus");
        }

        StringBuilder success = new StringBuilder();
        success.append("{ok, #").append(outputRecord).append("{");
        if (!recordFields.isEmpty()) {
            success.append("\n").append(String.join(",\n", recordFields)).append("\n");
        }
        success.append("}}");
        writer.write("$L;", success.toString());

        writer.dedent();
        writer.write(
                "decode_$L_response(#http_response{status = Status, headers = RespHeaders, body = Body}) ->",
                opName);
        writer.indent();
        writer.write("decode_$L_response_error(Status, RespHeaders, Body).", opName);
        writer.dedent();
        writer.write("");
    }

    private static void emitErrorDispatch(
            ErlangWriter writer,
            Model model,
            OperationShape op,
            SymbolProvider sp) {

        String opName = sp.toSymbol(op).getName();
        List<ShapeId> errors = new ArrayList<>(op.getErrors());

        writer.write("%% Error dispatch for $L.", op.getId());
        for (ShapeId errorId : errors) {
            StructureShape errShape = model.expectShape(errorId, StructureShape.class);
            String recName = recordName(sp.toSymbol(errShape));
            int httpStatus = errShape.hasTrait(HttpErrorTrait.class)
                    ? errShape.expectTrait(HttpErrorTrait.class).getCode()
                    : errShape.expectTrait(ErrorTrait.class).getDefaultHttpStatusCode();
            if (httpStatus <= 0) {
                continue;
            }
            writer.write("decode_$L_response_error($L, _Hdrs, Body) ->", opName, httpStatus);
            writer.indent();
            List<String> fields = buildErrorFields(errShape, sp);
            if (fields.isEmpty()) {
                writer.write("{error, #$L{}};", recName);
            } else {
                writer.write("{error, #$L{$L}};", recName, "\n    " + String.join(",\n    ", fields) + "\n");
            }
            writer.dedent();
        }

        writer.write("decode_$L_response_error(Status, _Hdrs, Body) ->", opName);
        writer.indent();
        writer.write("{error, {unknown_error, Status, Body}}.");
        writer.dedent();
        writer.write("");
    }

    private static List<String> buildErrorFields(StructureShape errShape, SymbolProvider sp) {
        List<String> fields = new ArrayList<>();
        for (MemberShape member : errShape.members()) {
            String fieldName = memberFieldName(sp, member);
            if (fieldName.equals("__beam_error_kind")) {
                continue;
            }
            fields.add(fieldName + " = undefined");
        }
        return fields;
    }

    private static void emitOpaqueRequestBody(
            ErlangWriter writer,
            Model model,
            List<HttpBinding> reqPayload,
            String method,
            SymbolProvider sp) {

        if (reqPayload.isEmpty()
                || method.equals("GET")
                || method.equals("DELETE")
                || method.equals("HEAD")) {
            writer.write("Body = <<>>,");
            return;
        }

        HttpBinding payload = reqPayload.get(0);
        MemberShape member = payload.getMember();
        String fieldName = memberFieldName(sp, member);
        String bindingVar = toBindingVar(fieldName);
        Shape target = model.expectShape(member.getTarget());

        if (target instanceof BlobShape || target.hasTrait(StreamingTrait.class)) {
            writer.write("Body = case $L of", bindingVar);
            writer.indent();
            writer.write("undefined -> <<>>;");
            writer.write("Value -> Value");
            writer.dedent();
            writer.write("end,");
            return;
        }

        writer.write("Body = case $L of", bindingVar);
        writer.indent();
        writer.write("undefined -> <<>>;");
        writer.write("Value when is_binary(Value) -> Value;");
        writer.write("Value -> to_binary(Value)");
        writer.dedent();
        writer.write("end,");
    }

    private static void emitHelpers(ErlangWriter writer) {
        writer.write("%% -- Private helpers --");
        writer.write("");
        writer.write("to_binary(V) when is_binary(V) -> V;");
        writer.write("to_binary(V) when is_list(V) -> list_to_binary(V);");
        writer.write("to_binary(V) when is_integer(V) -> integer_to_binary(V);");
        writer.write("to_binary(V) when is_float(V) -> float_to_binary(V);");
        writer.write("to_binary(true) -> <<\"true\">>;");
        writer.write("to_binary(false) -> <<\"false\">>;");
        writer.write("to_binary(V) when is_atom(V) -> atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("encode_query_value(V) when is_boolean(V) ->");
        writer.write("    atom_to_binary(V, utf8);");
        writer.write("encode_query_value(V) when is_integer(V) ->");
        writer.write("    integer_to_binary(V);");
        writer.write("encode_query_value(V) when is_float(V) ->");
        writer.write("    float_to_binary(V);");
        writer.write("encode_query_value(V) when is_binary(V) ->");
        writer.write("    V;");
        writer.write("encode_query_value(V) when is_atom(V) ->");
        writer.write("    atom_to_binary(V, utf8).");
        writer.write("");
        writer.write("uri_encode(Value) ->");
        writer.write("    uri_string:quote(Value).");
        writer.write("");
        writer.write("prefix_headers_to_list(_Prefix, undefined) ->");
        writer.write("    [];");
        writer.write("prefix_headers_to_list(Prefix, Map) when is_map(Map) ->");
        writer.write("    [{<<Prefix/binary, H/binary>>, to_binary(V)} || {H, V} <- maps:to_list(Map)].");
        writer.write("");
        writer.write("prefix_headers_from_list(Headers, Prefix) ->");
        writer.write("    Map = maps:from_list([");
        writer.write("        {binary:part(Name, byte_size(Prefix), byte_size(Name) - byte_size(Prefix)), Val}");
        writer.write("        || {Name, Val} <- Headers,");
        writer.write("           byte_size(Name) > byte_size(Prefix),");
        writer.write("           binary:part(Name, 0, byte_size(Prefix)) =:= Prefix");
        writer.write("    ]),");
        writer.write("    case maps:size(Map) of");
        writer.write("        0 -> undefined;");
        writer.write("        _ -> Map");
        writer.write("    end.");
        writer.write("");
    }

    private static List<String> buildPatternParts(
            SymbolProvider sp,
            List<HttpBinding> labels,
            List<HttpBinding> queries,
            List<HttpBinding> queryParams,
            List<HttpBinding> headers,
            List<HttpBinding> prefixHeaders,
            List<HttpBinding> reqPayload) {
        List<String> parts = new ArrayList<>();
        for (HttpBinding b : concat(labels, queries, queryParams, headers, prefixHeaders, reqPayload)) {
            String field = memberFieldName(sp, b.getMember());
            parts.add(field + " = " + toBindingVar(field));
        }
        return parts;
    }

    private static String buildPathExpression(
            String uriTemplate, List<HttpBinding> labels, SymbolProvider sp) {
        if (labels.isEmpty()) {
            return "<<\"" + uriTemplate + "\">>";
        }
        StringBuilder sb = new StringBuilder("<<");
        int pos = 0;
        while (pos < uriTemplate.length()) {
            int start = uriTemplate.indexOf('{', pos);
            if (start < 0) {
                sb.append("\"").append(uriTemplate.substring(pos)).append("\"");
                break;
            }
            if (start > pos) {
                sb.append("\"").append(uriTemplate, pos, start).append("\", ");
            }
            int end = uriTemplate.indexOf('}', start);
            String labelName = uriTemplate.substring(start + 1, end);
            if (labelName.endsWith("+")) {
                labelName = labelName.substring(0, labelName.length() - 1);
            }
            String fieldName = labelFieldName(labels, labelName, sp);
            sb.append("(uri_encode(to_binary(").append(toBindingVar(fieldName)).append(")))/binary");
            pos = end + 1;
            if (pos < uriTemplate.length()) {
                sb.append(", ");
            }
        }
        sb.append(">>");
        return sb.toString();
    }

    private static String labelFieldName(
            List<HttpBinding> labels, String locationName, SymbolProvider sp) {
        for (HttpBinding label : labels) {
            if (label.getLocationName().equals(locationName)) {
                return memberFieldName(sp, label.getMember());
            }
        }
        return BeamNameUtils.toSnakeCase(locationName);
    }

    private static String memberFieldName(SymbolProvider sp, MemberShape member) {
        return sp.toSymbol(member).getProperty("fieldName", String.class).orElseThrow();
    }

    private static String queryTupleKey(SymbolProvider sp, HttpBinding binding) {
        return "<<" + "\"" + memberFieldName(sp, binding.getMember()) + "\"" + ">>";
    }

    private static String headerTupleKey(SymbolProvider sp, HttpBinding binding) {
        return queryTupleKey(sp, binding);
    }

    private static boolean isStreamingBlob(Model model, MemberShape member) {
        Shape target = model.expectShape(member.getTarget());
        return target instanceof BlobShape && target.hasTrait(StreamingTrait.class);
    }

    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static String toBindingVar(String snakeField) {
        return BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    @SafeVarargs
    private static <T> List<T> concat(List<T>... lists) {
        List<T> out = new ArrayList<>();
        for (List<T> list : lists) {
            out.addAll(list);
        }
        return out;
    }

    private static List<OperationShape> containedOperationsSorted(Model model, ServiceShape service) {
        Set<OperationShape> contained = TopDownIndex.of(model).getContainedOperations(service);
        List<OperationShape> operations = new ArrayList<>(contained);
        operations.sort(Comparator.comparing(o -> o.getId().toString()));
        return operations;
    }
}
