package openriak.erlang.codegen;

import io.smithy.beam.core.BeamErlangLayout;
import io.smithy.beam.erlang.ErlangContext;
import io.smithy.beam.erlang.ErlangWriter;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolProvider;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.HttpBindingIndex;
import software.amazon.smithy.model.knowledge.TopDownIndex;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.StructureShape;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * JSON document encoders for structure HTTP request payloads.
 */
public final class ErlangOpenRiakJsonEmitter {

    public static final String JSON_SUFFIX = "json";

    private ErlangOpenRiakJsonEmitter() {}

    public static String jsonModuleName(BeamErlangLayout layout) {
        return layout.clientModuleName().replace("_client", "") + "_" + JSON_SUFFIX;
    }

    public static void emitJsonModule(ErlangContext ctx, ServiceShape service) {
        Model model = ctx.model();
        BeamErlangLayout layout = new BeamErlangLayout(
                ctx.settings(), service.getId().getNamespace(), service);
        String jsonFile = jsonModuleName(layout) + ".erl";
        String jsonModule = jsonModuleName(layout);
        HttpBindingIndex httpIndex = HttpBindingIndex.of(model);
        SymbolProvider sp = ctx.symbolProvider();

        Set<StructureShape> shapes = new LinkedHashSet<>();
        for (OperationShape op : containedOperationsSorted(model, service)) {
            for (var binding : httpIndex.getRequestBindings(op, software.amazon.smithy.model.knowledge.HttpBinding.Location.PAYLOAD)) {
                Shape target = model.expectShape(binding.getMember().getTarget());
                if (target instanceof StructureShape structureShape) {
                    collectStructureShapes(model, structureShape, shapes);
                }
            }
        }

        List<StructureShape> sorted = new ArrayList<>(shapes);
        sorted.sort(Comparator.comparing(s -> s.getId().toString()));

        List<String> exports = new ArrayList<>();
        for (StructureShape shape : sorted) {
            exports.add("encode_" + recordName(sp.toSymbol(shape)) + "/1");
        }

        ctx.writerDelegator().useFileWriter(jsonFile, writer -> {
            writer.write("%% JSON encoders for $L (generated).", service.getId());
            writer.write("%% DO NOT EDIT -- generated by openriak-erlang-codegen.");
            writer.write("-module($L).", jsonModule);
            writer.write("-include(\"$L\").", layout.typesHeaderFile());
            if (!exports.isEmpty()) {
                writer.write("-export([$L]).", String.join(",\n    ", exports));
            }
            writer.write("");

            for (StructureShape shape : sorted) {
                emitStructureEncoder(writer, model, shape, sp);
            }
        });
    }

    private static void collectStructureShapes(
            Model model, StructureShape root, Set<StructureShape> out) {
        if (!out.add(root)) {
            return;
        }
        for (MemberShape member : root.members()) {
            Shape target = model.expectShape(member.getTarget());
            if (target instanceof StructureShape structureShape) {
                collectStructureShapes(model, structureShape, out);
            } else if (target instanceof ListShape listShape) {
                Shape element = model.expectShape(listShape.getMember().getTarget());
                if (element instanceof StructureShape structureShape) {
                    collectStructureShapes(model, structureShape, out);
                }
            }
        }
    }

    private static void emitStructureEncoder(
            ErlangWriter writer,
            Model model,
            StructureShape shape,
            SymbolProvider sp) {

        String record = recordName(sp.toSymbol(shape));
        String typeName = sp.toSymbol(shape).getName();
        List<MemberShape> members = new ArrayList<>(shape.members());
        members.sort(Comparator.comparing(m -> memberFieldName(sp, m)));

        List<String> patternParts = new ArrayList<>();
        for (MemberShape member : members) {
            String fieldName = memberFieldName(sp, member);
            patternParts.add(fieldName + " = " + toBindingVar(fieldName));
        }
        String pattern = patternParts.isEmpty()
                ? ""
                : "\n    " + String.join(",\n    ", patternParts) + "\n";

        writer.write("-spec encode_$L($L) -> map().", record, typeName);
        writer.write("encode_$L(#$L{$L}) ->", record, record, pattern);
        writer.indent();
        writer.write("maps:from_list(lists:filtermap(fun");
        for (int i = 0; i < members.size(); i++) {
            MemberShape member = members.get(i);
            String wireKey = memberFieldName(sp, member);
            String encoded = encodeMemberValue(model, member, "V", sp);
            writer.write("    ({<<\"$L\">>, undefined}) -> false;", wireKey);
            if (i < members.size() - 1) {
                writer.write("    ({<<\"$L\">>, V}) -> {true, {<<\"$L\">>, $L}};", wireKey, wireKey, encoded);
            } else {
                writer.write("    ({<<\"$L\">>, V}) -> {true, {<<\"$L\">>, $L}}", wireKey, wireKey, encoded);
            }
        }
        writer.write("end, [");
        for (int i = 0; i < members.size(); i++) {
            MemberShape member = members.get(i);
            String wireKey = memberFieldName(sp, member);
            String varName = toBindingVar(memberFieldName(sp, member));
            String comma = i < members.size() - 1 ? "," : "";
            writer.write("    {<<\"$L\">>, $L}$L", wireKey, varName, comma);
        }
        writer.write("])).");
        writer.dedent();
        writer.write("");
    }

    private static String encodeMemberValue(
            Model model, MemberShape member, String varName, SymbolProvider sp) {
        Shape target = model.expectShape(member.getTarget());
        if (target instanceof StructureShape structureShape) {
            String nested = recordName(sp.toSymbol(structureShape));
            return "openriak_json:encode_" + nested + "(V)";
        }
        if (target instanceof ListShape listShape) {
            Shape element = model.expectShape(listShape.getMember().getTarget());
            if (element instanceof StructureShape structureShape) {
                String nested = recordName(sp.toSymbol(structureShape));
                return "[openriak_json:encode_" + nested + "(Item) || Item <- V]";
            }
        }
        return "V";
    }

    private static String memberFieldName(SymbolProvider sp, MemberShape member) {
        return sp.toSymbol(member).getProperty("fieldName", String.class).orElseThrow();
    }

    private static String recordName(Symbol symbol) {
        return symbol.getName().replace("()", "");
    }

    private static String toBindingVar(String snakeField) {
        return io.smithy.beam.core.BeamNameUtils.toCamelCaseVariable(snakeField);
    }

    private static List<OperationShape> containedOperationsSorted(Model model, ServiceShape service) {
        Set<OperationShape> contained = TopDownIndex.of(model).getContainedOperations(service);
        List<OperationShape> operations = new ArrayList<>(contained);
        operations.sort(Comparator.comparing(o -> o.getId().toString()));
        return operations;
    }
}
